### ISSUE TITLE
use istanbul generate coverage report get "MongoError: ReferenceError: __cov_DTXo50H7EG9GqwIkbYf5ig is not defined"

### ISSUE THREAD

**Issue by yinxin630** [Kingwl/Medivh-backend#11]
If use mocha to test, I will get 100% pass. But when I use istanbul to generate coverage report, I get a runtime error.

```
{ MongoError: ReferenceError: __cov_DTXo50H7EG9GqwIkbYf5ig is not defined :
_funcs1@:1:23

    at Function.MongoError.create (/Users/yinxin/Github/Medivh-backend/node_modules/mongodb-core/lib/error.js:31:11)
    at commandCallback (/Users/yinxin/Github/Medivh-backend/node_modules/mongodb-core/lib/topologies/server.js:1239:66)
    at Callbacks.emit (/Users/yinxin/Github/Medivh-backend/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at .messageHandler (/Users/yinxin/Github/Medivh-backend/node_modules/mongodb-core/lib/topologies/server.js:397:23)
    at Socket.<anonymous> (/Users/yinxin/Github/Medivh-backend/node_modules/mongodb-core/lib/connection/connection.js:302:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
  name: 'MongoError',
  message: 'ReferenceError: __cov_DTXo50H7EG9GqwIkbYf5ig is not defined :\n_funcs1@:1:23\n',
  ok: 0,
  errmsg: 'ReferenceError: __cov_DTXo50H7EG9GqwIkbYf5ig is not defined :\n_funcs1@:1:23\n',
  code: 139 }
```

**Comment by yinxin630** [comment]
Reference [this issues](https://github.com/gotwarlost/istanbul/issues/604). There was some conflict between mongoose and istanbul. You should define your map/reduce functions as strings rather than as functions. Then is should works.
